name: validate-pull-request
on: [pull_request]
jobs:
  build-projects:
    runs-on: windows-latest
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: dotnet build
  run-unit-tests:
    runs-on: windows-latest
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: dotnet test